const contacts = [
    {
        id: 1,
        firstname: "سمانه",
        lastname: "حمیدی",
        mobile: "09123456789",
        email: "user1@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=1",
        description: "توضیحات تستی",
    },
    {
        id: 2,
        firstname: "حمید",
        lastname: "اظهری",
        mobile: "09123456789",
        email: "user2@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=2",
        description: "توضیحات تستی",
    },
    {
        id: 3,
        firstname: "سعید",
        lastname: "حیدری",
        mobile: "09123456789",
        email: "user3@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=3",
        description: "توضیحات تستی",
    },
    {
        id: 4,
        firstname: "مجتبی",
        lastname: "احمدی",
        mobile: "09123456789",
        email: "user4@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=4",
        description: "توضیحات تستی",
    },
    {
        id: 5,
        firstname: "سوسن",
        lastname: "توحیدی",
        mobile: "09123456789",
        email: "user5@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=5",
        description: "توضیحات تستی",
    },
    {
        id: 6,
        firstname: "فرهاد",
        lastname: "وحیدی",
        mobile: "09123456789",
        email: "user6@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=6",
        description: "توضیحات تستی",
    },
    {
        id: 7,
        firstname: "علی",
        lastname: "محمدی",
        mobile: "09123456789",
        email: "user7@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=7",
        description: "توضیحات تستی",
    },
    {
        id: 8,
        firstname: "کامران",
        lastname: "اکبری",
        mobile: "09123456789",
        email: "user8@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=8",
        description: "توضیحات تستی",
    },
    {
        id: 9,
        firstname: "ناهید",
        lastname: "درویشی",
        mobile: "09123456789",
        email: "user9@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=9",
        description: "توضیحات تستی",
    },
    {
        id: 10,
        firstname: "زینب",
        lastname: "رضایی",
        mobile: "09123456789",
        email: "user10@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=10",
        description: "توضیحات تستی",
    },
    {
        id: 11,
        firstname: "عباس",
        lastname: "ماجدی",
        mobile: "09123456789",
        email: "user11@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=11",
        description: "توضیحات تستی",
    },
    {
        id: 12,
        firstname: "ابراهیم",
        lastname: "حسنی",
        mobile: "09123456789",
        email: "user12@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=12",
        description: "توضیحات تستی",
    },
    {
        id: 13,
        firstname: "حسن",
        lastname: "دهقان",
        mobile: "09123456789",
        email: "user13@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=13",
        description: "توضیحات تستی",
    },
    {
        id: 14,
        firstname: "سیروس",
        lastname: "فرهادی",
        mobile: "09123456789",
        email: "user14@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=14",
        description: "توضیحات تستی",
    },
    {
        id: 15,
        firstname: "کیوان",
        lastname: "خوندل",
        mobile: "09123456789",
        email: "user15@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=15",
        description: "توضیحات تستی",
    },
    {
        id: 16,
        firstname: "نگار",
        lastname: "پاشایی",
        mobile: "09123456789",
        email: "user16@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=16",
        description: "توضیحات تستی",
    },
    {
        id: 17,
        firstname: "فیروز",
        lastname: "شیرازی",
        mobile: "09123456789",
        email: "user17@gmail.com",
        avatar: "https://i.pravatar.cc/300?img=17",
        description: "توضیحات تستی",
    },
];

export default contacts;
